<?php
$_designerCollection = $block->getCollection();
$show_designer_name = $this->getConfig('designer_list_page/show_designer_name');
?>
<?php if ( $_designerCollection->count() ){ ?>
<?php $total = $_designerCollection->getSize(); ?>
<div class="designerlist">
	<div class="block-content">
		<?php foreach ($_designerCollection as $_designer) { ?>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="designer-item">
				<?php if($_designer->getThumbnailUrl()){ ?>
				<div class="designer-image"><a href="<?php echo $_designer->getUrl(); ?>" title="<?php echo $_designer->getName(); ?>"><img src="<?php echo $_designer->getThumbnailUrl(); ?>" alt="<?php echo $_designer->getName(); ?>"/></a></div>
				<?php } ?>
				<?php if($show_designer_name){ ?>
				<div class="designer-name"><a href="<?php echo $_designer->getUrl(); ?>" title="<?php echo $_designer->getName(); ?>"><?php echo $_designer->getName() ?></a></div>
				<?php } ?>
			</div>
		</div>
		<?php } ?>
	</div>
	<?php if($html = $block->getChildHtml('toolbar')){ ?>
	<div class="designer-toolbar  toolbar toolbar-products">
		<?php echo $block->getChildHtml('toolbar'); ?>
	</div>
	<?php } ?>
</div>
<?php }else{ ?>
<div class="message info empty"><div><?php echo __('We can\'t find designer matching the selection.'); ?></div></div>
<?php } ?>