<?php
$_designerCollection          = $block->getDesignerCollection();
$_helper                   = $this->helper('Lof\Designer\Helper\Data');
$title                     = $this->getConfig('designer_block/title');
$show_designer_name           = $this->getConfig('designer_block/show_designer_name');

$blockId                   = rand() . time() . uniqid();
$number_item_per_column    = (int)$this->getConfig('designer_block/number_item_per_column');
if($number_item_per_column == '' || $number_item_per_column == 0)
$number_item_per_column = 1;

$default_items             = $this->getConfig('designer_block/default_items');
$addition_class            = $this->getConfig('designer_block/addition_class');
$mobile_items              = (int)$this->getConfig('designer_block/mobile_items',1);
$tablet_small_items        = (int)$this->getConfig('designer_block/tablet_small_items',2);
$tablet_items              = (int)$this->getConfig('designer_block/tablet_items',3);
$portrait_items            = (int)$this->getConfig('designer_block/portrait_items',4);
$large_items               = (int)$this->getConfig('designer_block/large_items',5);
$dots                      = $this->getConfig('designer_block/dots');
$nav                       = $this->getConfig('designer_block/nav');
$nav_prev                  = $this->getConfig('designer_block/nav_prev');
$nav_next                  = $this->getConfig('designer_block/nav_next');
$loop                      = $this->getConfig('designer_block/loop');
$autoplay                  = $this->getConfig('designer_block/autoplay');
$autoplay_timeout          = (int)$this->getConfig('designer_block/autoplay_timeout',3000);
$autoplay_pauseonhover     = (int)$this->getConfig('designer_block/autoplay_pauseonhover');
$auto_play                 = $this->getConfig('designer_block/auto_play');
$rtl                       = $this->getConfig('designer_block/rtl');
$pretext                   = $_helper->filter($this->getConfig('designer_block/pretext'));
?>
<?php if ( $_designerCollection->count() ){ ?>
<?php
$_collection = [];
$i = $x = 0;
$total  = $_designerCollection->count();
$column = 8;
if($total%$number_item_per_column == 0){
	$column = $total/$number_item_per_column;
}else{
	$column = floor($total/$number_item_per_column)+1;
}
if($column<$default_items) $column = $default_items;
$i = $x = 0;
foreach ($_designerCollection as $_designer) {
	if($i<$column){
		$i++;
	}else{
		$i = 1;
		$x++;
	}
	$_collection[$i][$x] = $_designer;
} 
?>
<div class="block widget lof-widget designer-widget <?php echo $addition_class?$addition_class:'' ?>">
	<?php if($title){ ?>
	<div class="block-title"><strong><?php echo $title ?></strong></div>
	<?php } ?>
	<?php if($pretext!=''){ ?>
	<div class="pretext-html"><?php echo $pretext ?></div>
	<?php } ?>
	<div class="block-content designerowl-play">
		<ul id="lof-carousel<?php echo $blockId ?>" class="owl-carousel" data-rtl="<?php echo $rtl?"true":"false" ?>" data-loop="<?php echo $loop?"true":"false" ?>" data-nav="false" data-dot="<?php echo $dots?"true":"false" ?>" data-autoplay="<?php echo $autoplay?"true":"false" ?>" data-autoplay-timeout="<?php echo $autoplay_timeout ?>" data-pauonhover="<?php echo $autoplay_pauseonhover?"true":"false" ?>" data-mobile-items="<?php echo (int)$mobile_items ?>" data-tablet-small-items="<?php echo (int)$tablet_small_items ?>" data-tablet-items="<?php echo (int)$tablet_items ?>" data-portrait-items="<?php echo (int)$portrait_items ?>" data-large-items="<?php echo (int)$default_items ?>" data-large-max-items="<?php echo (int)$large_items ?>" >
			<?php foreach ($_collection as $_designerCollection) { ?>
			<li class="item">
				<?php foreach ($_designerCollection as $_designer) { ?>
				<div class="designer-item">
					<div class="designer-image"><a href="<?php echo $_designer->getUrl(); ?>" title="<?php echo $_designer->getName(); ?>"><img src="<?php echo $_designer->getThumbnailUrl(); ?>" alt="<?php echo $_designer->getName(); ?>"/></a></div>
					<?php if($show_designer_name){ ?>
					<div class="designer-name"><a href="<?php echo $_designer->getUrl(); ?>" title="<?php echo $_designer->getName(); ?>"><?php echo $_designer->getName() ?></a></div>
					<?php } ?>
				</div>
				<?php } ?>
			</li>
			<?php } ?>
		</ul>
		<?php if($nav){ ?>
		<a href="#" class="owl-left"><?php echo $nav_prev?$nav_prev:'Prev'; ?></a>
		<a href="#" class="owl-right"><?php echo $nav_next?$nav_next:'Next'; ?></a>
		<?php } ?>
	</div>
</div>
<?php } ?>
<script type="text/javascript">
	require(['jquery',
		<?php if($this->helper("Lof\Designer\Helper\Data")->getConfig("enable_owlcarousel")): ?>
		"Lof_All/lib/owl.carousel/owl.carousel.min",
		<?php endif; ?>
		'Lof_Designer/js/designer'], function () {});
</script>